#
# Faraday common essential drivers & utilities
#
obj-  :=
obj-n :=
obj-y :=

obj-$(CONFIG_SMP)           += platsmp.o headsmp.o
obj-$(CONFIG_HOTPLUG_CPU)   += hotplug.o

obj-$(CONFIG_PCI)           += serdes.o
obj-$(CONFIG_FTPCIE_CDNG2)  += ftpcie_cdng2.o

obj-$(CONFIG_ARMGTIMER)     += arm_global_timer.o
